version: '3.9'

networks:
  avito_test_network:
    driver: bridge

services:
  test_db:
    image: postgres:16
    container_name: avito_test_db
    networks:
      - avito_test_network
    environment:
      POSTGRES_USER: avito
      POSTGRES_PASSWORD: avito_password
      POSTGRES_DB: avito_test
    ports:
      - "5436:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U avito -d avito_test"]
      interval: 2s
      timeout: 2s
      retries: 5
    tmpfs:
      - /var/lib/postgresql/data

  test_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: avito_test_api
    networks:
      - avito_test_network
    environment:
      DB_HOST: test_db
      DB_PORT: 5432
      DB_NAME: avito_test
      DB_USER: avito
      DB_PASSWORD: avito_password
      DB_SSLMODE: disable
      APP_PORT: 8081
      PRODUCTION_TYPE: test
      ADMIN_TOKEN: admin
      USER_TOKEN: user
    ports:
      - "8081:8081"
    depends_on:
      test_db:
        condition: service_healthy
    command: ["/app/main"]
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8081/metrics"]
      interval: 3s
      timeout: 2s
      retries: 10
      start_period: 5s
